### ISSUE TITLE
make an empty default branch

### ISSUE THREAD

**Issue by Artoria2e5** [thor2002ro/unraid_kernel#10]
It might be a good idea to rename the current default branch and let an empty one take its place, only containing a README about what this thing is and where the actual up-to-date code is (i.e. in the hundreds of branches and tags). There's no way to get everything in a neat linear tree for a "master branch" anyways -- we keep branching off and adding unraid patches, because that's the whole point of this repo. Right now it looks like the code is 4-years-stale, when it's not.

Ideally the README can contain links to descriptions about additional tunable parameters introduced by unraid. Or just descriptions in your own words, if you feel like typing.

**Comment by thor2002ro** [comment]
sounds good
