### ISSUE TITLE
HuC firmware failing to load for A380 

### ISSUE THREAD

**Issue by Widzwill** [thor2002ro/unraid_kernel#11]
Hi - 
have been trialing **6.5rc1 20230715 o2 gcc 6.12.3** in order to user my A380 for hardware accelerated transcoding. However it seems the HuC firmware fails when loading?

Here is my log of the driver and firmware trying to load - 
 

> dmesg | grep i915
> [   24.719785] i915 0000:03:00.0: [drm] VT-d active for gfx access
> [   24.722270] i915 0000:03:00.0: vgaarb: deactivate vga console
> [   24.722312] i915 0000:03:00.0: [drm] Can't resize LMEM BAR - platform support is missing
> [   24.722354] i915 0000:03:00.0: [drm] Local memory IO size: 0x0000000010000000
> [   24.722366] i915 0000:03:00.0: [drm] Local memory available: 0x000000017c800000
> [   24.722375] i915 0000:03:00.0: [drm] Using a reduced BAR size of 256MiB. Consider enabling 'Resizable BAR' or similar, if available in the BIOS.
> [   24.737419] i915 0000:03:00.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=io+mem:owns=io+mem
> [   24.737849] i915 0000:03:00.0: Direct firmware load for i915/dg2_dmc_ver2_08.bin failed with error -2
> [   24.737857] i915 0000:03:00.0: [drm] Failed to load DMC firmware i915/dg2_dmc_ver2_08.bin. Disabling runtime power management.
> [   24.737861] i915 0000:03:00.0: [drm] DMC firmware homepage: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915
> [   24.745353] i915 0000:03:00.0: [drm] *ERROR* GT0: HuC firmware i915/dg2_huc_gsc.bin: fetch failed -ENOENT
> [   24.745362] i915 0000:03:00.0: [drm] GT0: HuC firmware(s) can be downloaded from https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915
> [   24.772982] i915 0000:03:00.0: [drm] GT0: GuC firmware i915/dg2_guc_70.bin version 70.5.1
> [   26.009003] i915 0000:03:00.0: [drm] GT0: GUC: excessive init time: 1203ms! [freq = 2400MHz, before = 2400MHz, status = 0x8002F034, count = 1, ret = 0]
> [   26.031089] i915 0000:03:00.0: [drm] GT0: GUC: submission enabled
> [   26.031100] i915 0000:03:00.0: [drm] GT0: GUC: SLPC enabled
> [   26.033750] i915 0000:03:00.0: [drm] GT0: GUC: RC enabled
> [   26.267162] [drm] Initialized i915 1.6.0 20201103 for 0000:03:00.0 on minor 0
> [   26.276509] i915 0000:03:00.0: [drm] Cannot find any crtc or sizes
> [   26.276670] i915 0000:03:00.0: [drm] Cannot find any crtc or sizes
> [   26.290812] mei_gsc i915.mei-gscfi.768: FW not ready: resetting: dev_state = 2 pxp = 0
> [   26.290837] mei_gsc i915.mei-gscfi.768: unexpected reset: dev_state = ENABLED fw status = 00000345 84670000 00000000 00000000 E0020002 00000000
> [   26.291564] mei_gsc i915.mei-gsc.768: FW not ready: resetting: dev_state = 2 pxp = 2
> [   26.291589] mei_gsc i915.mei-gsc.768: unexpected reset: dev_state = ENABLED fw status = 00000345 84670000 00000000 00000000 E0020002 00000000

> getent group render | cut -d: -f3
> 
> getent group video | cut -d: -f3
> 18
> getent group input | cut -d: -f3
> 71

wondering if this is due to MEI modules missing when the kernel was built? as referenced here https://gitlab.freedesktop.org/drm/intel/-/issues/7732

**Comment by adamgwaps** [comment]
@Widzwill  the solution is some module+.config modifucations mentioned in #12  needs to be done.

**Comment by thor2002ro** [comment]
I wanted to say forgot to update the firmware files...

**Comment by Widzwill** [comment]
Well I'm glad that it is just that, I was going mad wondering why it wasn't working 😅

I did try to do my own kernel build and ran into issues

**Comment by thor2002ro** [comment]
I will probably fix it with rc2 some time this week
