### ISSUE TITLE
Add documentation to build custom unraid kernel

### ISSUE THREAD

**Issue by Joly0** [thor2002ro/unraid_kernel#13]
Hey, it would be great if you could add documentation on how you are building the custom kernel for unraid with all your tweaks, etc

**Comment by sternskr** [comment]
https://gitlab.com/stefan99353/unraid-custom-kernel/-/blob/main/README.md

^Not exactly a full write up but it's the one I use to get the Unraid Kernel to support Arc GPUs until they hit 6.2 in the mainline

Might be helpful as a starting point or just for anyone else looking to build it

**Comment by opentux** [comment]
on unraid 6.12.6 with this guide 

I'm missing some libraries to finish the compilation. 

make oldconfig
make: error while loading shared libraries: libffi.so.7: cannot open shared object file: No such file or directory

do you use a vm or docker to compile a kernel this way?

**Comment by Joly0** [comment]
Maybe @thor2002ro could provide some documentation?

**Comment by thor2002ro** [comment]
I don't know what documentation you're looking for.... that link explains it all.....
you seem to lack basic libs....  install libffi7 .... it literally says it...

**Comment by Joly0** [comment]
> I don't know what documentation you're looking for.... that link explains it all.....
> you seem to lack basic libs....  install libffi7 .... it literally says it...

The link above describes how to build a custom kernel for unraid, but not how to integrate your specific tweaks. Thats what i was asking in my initial question.

**Comment by thor2002ro** [comment]
What? All the code is right there.... If you don't understand programming how do you expect to tweak it?  I don't I don't understand the question....😅
