### ISSUE TITLE
Mellanox Cards not assigneable in Unraid.

### ISSUE THREAD

**Issue by domrockt** [thor2002ro/unraid_kernel#14]
When i patch this Kernel on Unraid 6.12.4 my both my Mellanox cards( Unraid server 1, dual 25Gbe Connect 4x. Unraid server 2 100Gbe connect 4x)  wont be assigned to be a usable NIC.

Both are listed in the System Devices but are not usable/configurable as NICs ETH0- ETHX.

Is there a reason for that? Maybe because Mellanox is Nvidia right now?

 I want to use my Intel ARC 770 for Docker use. 

thx for any info on that.

regards

**Comment by thor2002ro** [comment]
there seams to be a driver for Ethernet Mellanox  in the kernel and its in the release.... 

> CONFIG_NET_VENDOR_MELLANOX=y
CONFIG_MLX4_EN=m
CONFIG_MLX4_CORE=m
CONFIG_MLX4_DEBUG=y
CONFIG_MLX4_CORE_GEN2=y
CONFIG_MLX5_CORE=m
> CONFIG_MLX5_FPGA is not set
> CONFIG_MLX5_CORE_EN is not set
> CONFIG_MLXSW_CORE=m
CONFIG_MLXSW_CORE_HWMON=y
CONFIG_MLXSW_CORE_THERMAL=y
CONFIG_MLXSW_PCI=m
CONFIG_MLXSW_I2C=m
CONFIG_MLXSW_SPECTRUM=m
CONFIG_MLXSW_MINIMAL=m
CONFIG_MLXFW=m



should work and maybe it needs some configuration....

**Comment by domrockt** [comment]
So i got ALOT of mlx5 errors on boot 
-16 and some more 

So the Card and Drivers are found but the Card wont initialize.

When i downgrade the Card is directly acknowledged and works just fine. Maybe i try an older version, tommorow. 

Can i use this [6.2 20230220 o2 gcc 6.11.5] on Unraid  6.12.4? or do i need the newest?

**Comment by thor2002ro** [comment]
dont try kernels for 6.11 they wont work

**Comment by thor2002ro** [comment]
try 6.6rc7 maybe they fixed it in this

**Comment by domrockt** [comment]
"error while getting interface flags no such device"
it seems that the driver is not starting but it is there. 

thank you for responding it seems i must wait for Unraid to update the Linux version.

**Comment by thor2002ro** [comment]
By what you are saying sounds like the mainline driver is busted....

**Comment by domrockt** [comment]
[Mellanox CX4121A IBM 01GR253 Dual-Port SFP28]
[Mellanox Huawei ConnextX CX455A 06030347 1-Port NIC 100G QSFP28]

both Connect 4x Cards 

mlx5 kernel driver and Kernel module is loaded in  6.12.4 and works just fine.

yea it sounds so but for this long? i mean we are talking server grade NICs here :D

**Comment by thor2002ro** [comment]
Servers don't usualy use latest kernels server farms usualy use 5.10, 5.15 kernels

**Comment by thor2002ro** [comment]
6.7 has new Mellanox stuff in it .... see if it works if you want...

**Comment by domrockt** [comment]
Hey cool you mentioned back to me,  i got knee deep in modifiing the Kernel myselfe and added all needed functions. It works now fine with my own Kernel Package, but thx for not forgetting me :D
