### ISSUE TITLE
ZFS Support

### ISSUE THREAD

**Issue by RachaelsDen** [thor2002ro/unraid_kernel#15]
Any chance we can get a more recent build with ZFS support?  You seemed to have dropped it in the more recent 6.6 kernels.

**Comment by thor2002ro** [comment]
they still have the latest zfs versions included... I just removed the note since no one complained so I removed the untested note...

**Comment by RachaelsDen** [comment]
Ok, I just know when I checked the modules, the ZFS one was missing.  I'll try the latest and if everything looks good, I'll close this.
