### ISSUE TITLE
question for rebar

### ISSUE THREAD

**Issue by opentux** [thor2002ro/unraid_kernel#17]
Hi,

thanks for this kernel. 
I test and is ok for me...
but i have a question. do you activate "resize bar patch" (for use with nvidia, intel or amd for pci passthrough)

exemple with an post on unraid forum 
https://forums.unraid.net/topic/133192-vm-gpu-passthrough-resizable-bar-support-in-61-kernel/page/3/

thanks in advance

**Comment by thor2002ro** [comment]
patch is already included in the kernel since its mainline....
