### ISSUE TITLE
Network issues with 6.12.6 releases

### ISSUE THREAD

**Issue by mLgz0rn** [thor2002ro/unraid_kernel#18]
I seem to be having some weird network issues using the 6.12.6 releases.
My vm's and docker containers will not get network connection and/or host access when using vhost0 for my vm's and bond0 for containers.
This is working perfectly fine on the 6.12.4 releases.
Don't know if it's driver related or what.

I got 2 Realtek 8125 NIC's and I tried updating the drivers using the RTL8125(B) PCI Drivers package from the CA apps.
Since i'm also getting a warning from the fix common problems plugin
_(Realtek R8125 NIC found - The default Realtek NIC driver is known to have issues, consider installing the driver plugin from Community Applications if you are having stability issues or trouble with networking. Search for: r8125 in Community Applications, install the plugin and reboot your server.)_
But i'm unable to, it won't download them

**Comment by RileyBoi** [comment]
I'm running into the same issue. I also have a Realtek 8125 NIC. I rolled back my kernel, installed the community app, then upgraded the kernel again, but that didn't resolve my issues. However, before installing the community app, an error would appear letting me know that the eth0 interface did not exist, and it;s state would be down, after installing the plugin that error is gone and the interface is up, though cannot even ping the gateway.

I haven't dug much into the unRAID logs yet, but I'll share if I find something useful.

**Comment by Knallli** [comment]
Having a similar problem. The same NIC (RTL8125 rev 05) doesn’t work at all on the latest 6.7.2. System boots but can’t get an IP for the host.

**Comment by thor2002ro** [comment]
RTL8125  should work out of the box with the build in kernel module r8169 .... you should remove the unraid package for r8125 and reboot since I suspect its interfering with the build in module

**Comment by Knallli** [comment]
> RTL8125 should work out of the box with the build in kernel module r8169 .... you should remove the unraid package for r8125 and reboot since I suspect its interfering with the build in module

I don’t have the unraid package installed. 6.7.0 works completely fine for me though.

**Comment by Knallli** [comment]
> > RTL8125 should work out of the box with the build in kernel module r8169 .... you should remove the unraid package for r8125 and reboot since I suspect its interfering with the build in module
> 
> I don’t have the unraid package installed. 6.7.0 works completely fine for me though.

newest one does not work either

Edit: I got networking up by manually invoking dhcpcd via the host cli. I am not sure why it is not autostarting on those kernel versions.

Edit2: Seems like linux bridges are broken for networking? once I enable them everything breaks again. If Bridges are disabled everything works on latest.

**Comment by thor2002ro** [comment]
I'm using bridges and they work fine ... maybe its a combination with the RTL8125.....
