### ISSUE TITLE
Nested ESXi SVM(AMD) kernel patch

### ISSUE THREAD

**Issue by mikeyo** [thor2002ro/unraid_kernel#19]
Hi

Any chance we can have a custom kernel compiled for UNRAID that includes the fix for a long standing KVM/AMD bug as detailed here?https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2008583

It looks like the fix is in kernel 6.8rc1+

Thanks

**Comment by thor2002ro** [comment]
I'll try making an 6.8 kernel this weekend...

**Comment by mikeyo** [comment]
> I'll try making an 6.8 kernel this weekend...

Amazing, thanks so much. I really want to test some nested virtualisation on my amd box and don't want to use proxmox.

**Comment by thor2002ro** [comment]
built 6.8rc3.....

**Comment by mikeyo** [comment]
> built 6.8rc3.....

Thanks, I can confirm that this build fixed the AMD nested ESXi issue.
