### ISSUE TITLE
6.12.8 release

### ISSUE THREAD

**Issue by adamgwaps** [thor2002ro/unraid_kernel#20]
Is it safe to use on 6.12.8 release? 

Thanks!

**Comment by mikeyo** [comment]
I just tried it on 6.12.8 and it didn't play nice, errors on boot and no IP address. @thor2002ro, any chance we could get the latest kernel to work with 6.12.8? I just bought a 14700 CPU and current UNRAID linux kernel is not supporting it very well.

**Comment by maydaytek** [comment]
Similar behavior for me, no IP address on boot. Unsure if this is related to some of the other issues related to DHCP but for now I'll stay on 6.12.6

**Comment by mikeyo** [comment]
@thor2002ro thanks for compiling 6.12.8

**Comment by thor2002ro** [comment]
yw
