### ISSUE TITLE
Unraid 16.2.8

### ISSUE THREAD

**Issue by confuzedplayer** [thor2002ro/unraid_kernel#21]
Updated Unraid to 16.2.8 and the ARC is not working. I used the pre-release of 16.2.8 and some reason my unraid wont boot up at all. I restored the original files and it boots up to unraid 16.2.8 but now my ARC doesnt work. I rolled back my unraid server to 16.2.6 with 6.7.0 20240108 o2 clang18 thinLTO 6.12.6 and arc still works for that. 

Was wondering if i was using a wrong version?

**Comment by thor2002ro** [comment]
other versions other than https://github.com/thor2002ro/unraid_kernel/releases/tag/20240220 are not meant for 6.12.8.... carefull in 6.8 there are 2 drivers for arc I915 and xe if it doesnt work wait for the next version .... maybe something is broken in this rc revision

**Comment by confuzedplayer** [comment]
Ok thank you
