### ISSUE TITLE
alx module patch for WoL

### ISSUE THREAD

**Issue by mdrjr** [thor2002ro/unraid_kernel#23]
Can you add this patch: https://github.com/AndiWeiss/alx-wol/blob/master/patches/0001-alx-wol-v6.3.patch
To enable Wake-On-Lan for Killer network cards? 

It was removed from the Linux kernel due to some cards having a hardware bug that causes WoL events without an actual WoL event.
I'm testing on my server and so far it looks ok.

**Comment by thor2002ro** [comment]
sure I'll add it in the next one looks harmless

**Comment by thor2002ro** [comment]
6.8rc6 has the patch

**Comment by mdrjr** [comment]
Thanks for adding it! 
Tested and WoL works perfectly now on two killer network cards!
