### ISSUE TITLE
6.8 issues sata issues

### ISSUE THREAD

**Issue by mdrjr** [thor2002ro/unraid_kernel#25]
While using the newer 6.8 for my network WoL support I've found that when using ASMedia 1166 PCI-E to SATA adapter on some reboot a few of the HDD's won't be recognized.

Happens at random.
Rolling back to 6.7 and the issue is gone.

**Comment by thor2002ro** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/ata?h=v6.8-rc7&id=0077a504e1a4468669fd2e011108db49133db56e
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/ata?h=v6.8-rc7&id=9815e39617541ef52d0dfac4be274ad378c6dc09

seams the card is forced to report 6 ports... might be the issue

**Comment by thor2002ro** [comment]
ok... might be a bigger issue with 6.8 I had to do some restarts installing some new hdds and ran into all sorts of sata errors ..... and I dont have any ASMedia satas... only amd sata onboard and a marvell sata controller .... I'll leave 6.8rc's alone for a while untill it gets to 6.8.1-2-3....

**Comment by thor2002ro** [comment]
released 6.7.9 with killer patch...

**Comment by thor2002ro** [comment]
I suggest you use the gcc version btw.... in some testings the clang had subtle  issues
