### ISSUE TITLE
6.12.9 bonding broken again

### ISSUE THREAD

**Issue by mLgz0rn** [thor2002ro/unraid_kernel#27]
Hello!

in unraid 6.12.9 bonding seems to be broken again.
Don't know if they have reversed what was changed or what.
But I do not get any external connection when bonding is enabled.
I had to manually set the bond0 interface to down before I could even reach the unraid gui on the machine hosting it.
After disabling bonding completely the internet connection came back.

**Comment by hammoudma** [comment]
@mLgz0rn hey I am facing a similar issue, I only need the custom kernel so that I can use my Arc GPU for transcoding. Any tips or steps i can follow to fix the bonding issue? (also does it have any side effects u know of)

**Comment by thor2002ro** [comment]
this should fix it for 6.12.9 https://github.com/thor2002ro/unraid_kernel/releases/tag/20240331

**Comment by mLgz0rn** [comment]
Yup that fixed it!
Thank you!
