### ISSUE TITLE
Any way to include firmware for 6.10RC5?

### ISSUE THREAD

**Issue by flyize** [thor2002ro/unraid_kernel#3]
I've got an Alder Lake that's not so useful without the 5.18 kernel.

**Comment by thor2002ro** [comment]
does the kernel boot on intel?
the firmware file is in older releases 20220412-5.18rc2 is the last one....

**Comment by flyize** [comment]
It does!

Anything I'd need to do to RC2 to make it work in 6.10RC5?

**Comment by thor2002ro** [comment]
add md_mod.unraid_patch=22 to the kernel cmdline for 6.10rc4/rc5 its detailed in the release section

**Comment by flyize** [comment]
Ahhh, didn't know that would work on all versions! Thanks!

**Comment by thor2002ro** [comment]
no only on last version.... just get the fw from 5.18rc2 and release 5.18rc5

**Comment by flyize** [comment]
@thor2002ro Seems the array won't start with that version, as it says I have an incompatible md version.

edit: Oh I think I misunderstood. I only need the firmware file from the old version.

**Comment by thor2002ro** [comment]
Yes

**Comment by flyize** [comment]
@thor2002ro I'm not sure if you can help at all, but I figure I'll ask. When doing hardware transcoding on Alder Lake iGPU, with the default 5.15 kernel, the whole thing locks up. With your kernel only the Plex container crashes. Any ideas, or is this not something you can help with?

**Comment by thor2002ro** [comment]
I have no experience with plex... But found this...
https://www.reddit.com/r/PleX/comments/so1hvk/alder_lake_on_arch_gpu_hangs_using_qsv/?utm_medium=android_app&utm_source=share

You could also run an ffmpeg docker and test out if encoding is working outside of plex...

**Comment by flyize** [comment]
@thor2002ro Will this same version work with RC6/7? More specifically, do we still use md_mod.unraid_patch=22?

(Also, I still can't get Plex to work with Intel QS, but its clearly not 'your' issue. Thanks for taking a look though!)

**Comment by thor2002ro** [comment]
Will work on any version  unless they change any driver functionality you just need to input the connect patch level the unraid version requires.... You can find it in the log at boot of the stock kernel...

**Comment by thor2002ro** [comment]
It could be many things if the gpu requires custom / new stuff the dockers usually use old ubuntu 20.04 as base and that has old mesa i usually make my custom dockers with newer bases or packages.... Since i use amd gpu vaapi most docker are missing the required packages outright
