### ISSUE TITLE
Include Bluetooth and Coral Drivers

### ISSUE THREAD

**Issue by Naticus** [thor2002ro/unraid_kernel#30]
Would it be possible for you to also add support for Bluetooth and Coral drivers?  Unfortunately the official kernel has no support for my Arc A310, but this kernel has no support for both Bluetooth and Coral, so I'm caught in a no-win situation on which kernel to use.

**Comment by thor2002ro** [comment]
there https://github.com/thor2002ro/unraid_kernel/releases/tag/20240518-1

**Comment by Naticus** [comment]
Thank you so much! Can confirm everything is working once more.
