### ISSUE TITLE
add binder_linux,ashmem_linux support

### ISSUE THREAD

**Issue by zh522130** [thor2002ro/unraid_kernel#31]
Hello,

I am looking to run redroid on unraid, but I've noticed that unraid is missing support for binder_linux and ashmem_linux. I attempted to compile with reference to your code at https://gitlab.com/stefan99353/unraid-custom-kernel/-/tree/main, and upon comparison with the files you have released, I found that the directory modules\6.9.1-thor-Unraid is missing the 'extra' folder. Additionally, the size of the .xz files is mostly different from the ones you provided. 

As I am not too familiar with Linux, I was wondering if you could include support for binder_linux and ashmem_linux in your firmware.

**Comment by thor2002ro** [comment]
ashmem_linux is long gone from android.... it has been removed from the kernel for some time.... 5.x era.... binder should suffice

**Comment by thor2002ro** [comment]
here https://github.com/thor2002ro/unraid_kernel/releases/tag/20240520

**Comment by zh522130** [comment]
> here https://github.com/thor2002ro/unraid_kernel/releases/tag/20240520

Thank you very much; your efficiency is impressive. I'll test it out in a moment.

**Comment by zh522130** [comment]
I still can't get redroid to run, and I'm not sure what the issue is. Nonetheless, I appreciate your prompt addition of binder support.
