### ISSUE TITLE
Implement Ugreen NAS HDD LED status light support

### ISSUE THREAD

**Issue by ampersandru** [thor2002ro/unraid_kernel#33]
Wondering if it is possible to implement the new UGreen NAS HDD LED status lights into this kernel for Unraid:
https://github.com/miskcoo/ugreen_dx4600_leds_controller

**Comment by thor2002ro** [comment]
this should do it https://github.com/thor2002ro/unraid_kernel/releases/tag/20240619

**Comment by DjSni** [comment]
fyi, ich777 will do a plugin for unraid.
