### ISSUE TITLE
6.10.rc5 build?

### ISSUE THREAD

**Issue by lunks** [thor2002ro/unraid_kernel#34]
Hi, it seems tone-mapping on Intel ARC has been fixed on 6.10 rcs. Can we have a build with it?

**Comment by thor2002ro** [comment]
that's something I have been working on but its more complicated to bring it up... since there's some modifications to the blk block thats I havent had time to investigate... needs some modifications to the unraid driver again...

**Comment by mLgz0rn** [comment]
> Hi, it seems tone-mapping on Intel ARC has been fixed on 6.10 rcs. Can we have a build with it?

I'm on 6.9.5 and it's working fine there?
