### ISSUE TITLE
With 6.10RC8 (and possibly before) shutdown/restart doesn't work.

### ISSUE THREAD

**Issue by flyize** [thor2002ro/unraid_kernel#4]
If I try to shutdown or restart, the system hangs and I have to power it off manually. Not sure how this works, but it seems Unraid doesn't detect this as an unclean shutdown, as no parity check is started after reboot.

Not sure what to provide as far as logging to assist.

**Comment by thor2002ro** [comment]
no idea... I didn't see any issues like that on my system....

**Comment by flyize** [comment]
I confirmed with the latest kernel, both shutdown and reboot work correctly. Thanks!

**Comment by thor2002ro** [comment]
Cool means it was some mainline rc bug... Glad it worked out...
