### ISSUE TITLE
How to determine md_mod.unraid_patch value?

### ISSUE THREAD

**Issue by gritstub** [thor2002ro/unraid_kernel#5]
How should we determine the `md_mod.unraid_patch=` value?
Specifically, what should be used for 6.10.0 final?

**Comment by thor2002ro** [comment]
booting unraid with stock kernel... in system log about 75% down the log you should see something like
'May 19 04:48:19 Tower emhttpd: Unraid(tm) System Management Utility version 6.10.0
May 19 04:48:19 Tower emhttpd: Copyright (C) 2005-2021, Lime Technology, Inc.
May 19 04:48:20 Tower emhttpd: shcmd (3): /usr/local/emhttp/webGui/scripts/update_access
May 19 04:48:20 Tower sshd[1714]: Received signal 15; terminating.
May 19 04:48:21 Tower sshd[14688]: Server listening on 0.0.0.0 port 22.
May 19 04:48:21 Tower sshd[14688]: Server listening on :: port 22.
May 19 04:48:22 Tower emhttpd: shcmd (6): modprobe md-mod super=/boot/config/super.dat
May 19 04:48:22 Tower kernel: md: unRAID driver 2.9.17 installed`
the unraid patch is the last nr in 2.9.17 so in this case is 17....

as far as I looked the version didn't change from the last one I posted ... 22 for unraid 6.10rc4/6.10rc5

**Comment by gritstub** [comment]
Thanks! So in the case of 6.10.0 final, this should be 22!

```md: unRAID driver 2.9.22 installed```
