### ISSUE TITLE
5.18 has been released. Yay!

### ISSUE THREAD

**Issue by flyize** [thor2002ro/unraid_kernel#6]
When you have some time...

Also, does it matter to have an updated bzfirmware.7z? Any chance it might help my Alder Lake?

**Comment by thor2002ro** [comment]
sometimes firmware files are added or updated.... if a firmware files is missing and you have a device that depends on it it wont work

**Comment by flyize** [comment]
@thor2002ro Sorry to bother friend, but any chance we could get another kernel build? It's suggested here that the latest version will work with Alder Lake and HW transcoding.

https://forums.unraid.net/bug-reports/prereleases/69x-610x-intel-i915-module-causing-system-hangs-with-no-report-in-syslog-not-alder-lake-r1674/?do=findComment&comment=19828

Is there any way for me to easily do this? That way I won't have to bother you!
