### ISSUE TITLE
Unraid won't reboot

### ISSUE THREAD

**Issue by michaeldtsa** [thor2002ro/unraid_kernel#7]
For both 5.18 and 5.18.3 Kernels with Unraid 6.10.0, the system won't reboot. The console says "Rebooting." but nothing happens.

**Comment by flyize** [comment]
I've had that happen a couple of times. And then it seems to work after that. No idea what the deal is, but Unraid doesn't seem to detect it as an unclean shutdown.

**Comment by michaeldtsa** [comment]
Never works for me with this Kernel. Always stops at "Rebooting." and then does nothing :(

It's not a huge deal. I don't restart much, but sometimes it's needed to fix a problem when testing plex transcoding, and restarting is easier than shut-down and manual power on (server is in an awkward location.)

**Comment by thor2002ro** [comment]
this kernel is optimized for zen3 cpus running it on anything else and issues might apear...
